### ISSUE TITLE
When  deploy  on  ubuntu  16.04 with

### ISSUE THREAD

**Issue by QQ40451** [foraern/ethos-panel#20]
![qq 20181021215336](https://user-images.githubusercontent.com/39938851/47267869-dd94a480-d57b-11e8-9180-99b07f97b0bb.png)

**Comment by QQ40451** [comment]
apache2  php7  mysql5  ;error occur 。。

**Comment by ricardo-nolan** [comment]
Hi,

I see you have all errors displaying.
Turn off php errors. This happens because you don't have any active rigs, so it throws up php warnings, which the datatables can't process (nor do you want a bunch of notices displaying).
I'll eventually put in improved error handling, but haven't had a chance yet.

**Comment by QQ40451** [comment]
thanks for reply。i ’ll fill data for a test。
